### ISSUE TITLE
Cannot GET //nodeadmin

### ISSUE THREAD

**Issue by danielebuso** [nodeadmin/nodeadmin#12]
Hello, I'm trying to get nodeadmin working but it gives me this error when i navigate to mydomain.com/db/nodeadmin

`Cannot GET //nodeadmin`

Here is my node.js app

``` javascript
var express = require('express');
var app = express();

var nodeadmin = require('nodeadmin');
app.use(nodeadmin(app));
app.listen(3200);
```

And here is my nginx configuration for the `/db` location

``` nginx
location /db {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://127.0.0.1:3200/;
        proxy_redirect off;
    }
```

Thanks in advance for any help

**Comment by taylorleh** [comment]
@danielebuso is there a reason you are configuring your base route with /db/nodeadmin? Are the services failing (console errors) or is this a nginx server error. You won't be able to access the dashboard until you have authenticated at http://<yourdomain.com[:port]>/nodeadmin

nodeadmin is configured with an absolute path. you can find this under middleware/index.js 

```javascript
app.use('/nodeadmin', express.static(__dirname + '/public'));
```

some areas may not work properly if defining your own entry point. Also, are you including your configured port in your request?
