### ISSUE TITLE
Custom database port

### ISSUE THREAD

**Issue by spywhere** [nodeadmin/nodeadmin#24]
Is there anyway I can configure the database port?

I did try `host:port` but it's ends up with ` We couldn't find the host that you provided. Double check to make sure you typed it in correctly and try again.`

When I configure the port to `3306` (default MySQL port) it's work perfectly.

**Comment by taylorleh** [comment]
@spywhere there isn't an option to configure the port as of right now. However, you can do so easily by adding a 'port' key in /middleware/auth/authcontroller.js between lines 8-13. Hope this helps.

**Comment by spywhere** [comment]
Thanks for a workaround. However, as I file the issue, I want it as a configuration as it would be a lot easier to configure the port instead of editing the code.

**Comment by sjb933** [comment]
See my pull request addressing this issue:  https://github.com/nodeadmin/nodeadmin/pull/28

**Comment by sjb933** [comment]
@taylorleh you can close this issue now.  Thanks for accepting the pull request.  Publish an NPM update if you don't mind.  Cheers!
