### ISSUE TITLE
Fails to load socket.io.js

### ISSUE THREAD

**Issue by lluiscab** [nodeadmin/nodeadmin#34]
I have just installed nodeadmin and created a basic express app to test it:

```var express = require('express');
var app = express();
 
var nodeadmin = require('nodeadmin');
app.use(nodeadmin(app));
app.listen(8081);
```

I found a bug! (yay!)

Loading socket.io.js from `/nodeadmin/node_modules/socket.io-client/socket.io.js` returns a 404 which seems to break some angular js code and the stats on the dashboard.

Also just to point out, the edit privileges UI for users isn't "great". Could it be changed to just a checkbox?

**Comment by svensklave** [comment]
Should be
/nodeadmin/node_modules/socket.io-client/dist/socket.io.js

**Comment by CherryDT** [comment]
@svensklave OK but how to I make nodeadmin use the new URL then? `app.use(nodeadmin(app))` is all the interaction I have with the code...

**Comment by ThePlatzhalter** [comment]
@CherryDT I don't know if this is still an issue for you, but what I did was simply creating a symbolic link from `node_modules/socket.io-client/dist/socket.io.js` to `node_modules/socket.io-client/socket.io.js`. That way you don't have to change anything in the actual code.

**Comment by CherryDT** [comment]
That's not such a good solution unfortunately because it can break on package updates, and deployment systems assume that the node_modules folder is not tampered with. So it sounds very fragile to me.
